services:
  aspis_runner:
    image: aspis
    container_name: aspis_runner
    volumes:
      - .././testing/tests/:/workspace/ASPIS/tmp/
    entrypoint: ["/workspace/ASPIS/aspis.sh", "--llvm-bin", "/workspace/llvm-project-21.1.8.src/build/bin"]